version: "3.7"

services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
        - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
volumes:
  database_data:
    driver: local